name: Build and deploy
on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      registry: ${{ steps.set_var.outputs.registry }}
      repo: ${{ steps.set_var.outputs.repo }}
      image_tag: ${{ steps.set_var.outputs.image_tag }}
    steps:
      - name: Set Var
        env:
          ECR_REGISTRY: registry
          ECR_REPOSITORY: repo
          IMAGE_TAG: v1
        id: set_var
        run: | 
          echo "setting var"
          echo "::set-output name=registry::$ECR_REGISTRY"
          echo "::set-output name=repo::$ECR_REPOSITORY"
          echo "::set-output name=image_tag::$IMAGE_TAG"

  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Use Var
        id: use_var
        run: |
          echo ${{ needs.ci.outputs.registry }}/${{ needs.ci.outputs.repo }}:${{ needs.ci.outputs.image_tag }}
