name: Build and deploy
on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      build_id: ${{ steps.set_var.outputs.build_id }}
    steps:
      - name: Set Var
        env:
          ECR_REGISTRY: registry
          ECR_REPOSITORY: repo
          IMAGE_TAG: v1
        id: set_var
        run: | 
          echo "setting var"
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

  cd:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Use Var
        id: use_var
        run: echo ${{ needs.ci.outputs.image }}
